import { createClient } from '@supabase/supabase-js';
import { JournalEntry } from '../types';

// Configuração do Supabase com as credenciais fornecidas
const supabaseUrl = 'https://godkhytkeqsnfpghtqhn.supabase.co';
const supabaseKey = 'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImdvZGtoeXRrZXFzbmZwZ2h0cWhuIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjQ2NjgzNjksImV4cCI6MjA4MDI0NDM2OX0.sk8SRcA2ZuTzFRpg9FP4PpFiVsHTZNamF-ruTnanyU8';

export const supabase = createClient(supabaseUrl, supabaseKey);

/*
  === IMPORTANTE: CÓDIGO SQL EXATO PARA O SUPABASE ===
  
  Copie e cole o código abaixo EXATAMENTE como está no "SQL Editor" do Supabase:

  create table if not exists public.journal_entries (
    id bigint generated by default as identity primary key,
    created_at timestamp with time zone default now(),
    user_name text,
    date text,
    positive_highlight text,
    contribution_idea text,
    rewind_change text,
    tomorrow_actions text[],
    productivity_score smallint,
    productivity_reason text,
    gratitude_list text[],
    forgiveness_self text,
    forgiveness_others text,
    learning_conclusion text,
    ai_feedback text
  );

  alter table public.journal_entries enable row level security;

  create policy "Permitir inserção publica"
  on public.journal_entries
  for insert
  to anon
  with check (true);

  create policy "Permitir leitura publica"
  on public.journal_entries
  for select
  to anon
  using (true);
*/

export const saveJournalEntry = async (entry: JournalEntry, aiFeedback: string) => {
  try {
    console.log("Iniciando salvamento no Supabase...");
    
    const { data, error } = await supabase
      .from('journal_entries')
      .insert([
        {
          user_name: entry.userName,
          date: entry.date,
          positive_highlight: entry.positiveHighlight,
          contribution_idea: entry.contributionIdea,
          rewind_change: entry.rewindChange,
          tomorrow_actions: entry.tomorrowActions, // Supabase aceita array de strings direto
          productivity_score: entry.productivityScore,
          productivity_reason: entry.productivityReason,
          gratitude_list: entry.gratitudeList, // Supabase aceita array de strings direto
          forgiveness_self: entry.forgivenessSelf,
          forgiveness_others: entry.forgivenessOthers,
          learning_conclusion: entry.learningConclusion,
          ai_feedback: aiFeedback
        },
      ])
      .select();

    if (error) {
      console.error('Erro detalhado ao salvar no Supabase:', error);
      return { success: false, error };
    }

    console.log("Dados salvos com sucesso:", data);
    return { success: true, data };
  } catch (err) {
    console.error('Erro inesperado ao salvar:', err);
    return { success: false, error: err };
  }
};
